version: '3.9'

services:
  postgres:
    image: postgres:15.4
    container_name: flavor-postgres
    restart: no
    environment:
      - TZ=${TIMEZONE}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - flavor-db:/var/lib/postgresql/data:rw

  minio:
    image: minio/minio:RELEASE.2024-02-17T01-15-57Z
    container_name: flavor-minio
    restart: no
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD} 
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    volumes:
      - flavor-minio:/data:rw
      # you may use a bind-mounted host directory instead,
      # so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/storage/data:/data:rw
    command: server /data --console-address ":9001"

volumes:
  flavor-db: {}
  flavor-minio: {}